// Auto-generated by sync_sheet_public_license.py — do not edit by hand
var HMAC_SECRET = "hF9kQ2mZ7vX1pR4nL8wB6cT3yD5sG0aJeU2iO9rK4lM7nP1qV8xZ3bN6";
var EMBEDDED_ROWS = [{"key":"Admin","days":10000,"device":"IPF-4CE44B7C2A8A","status":"CHẠY"},{"key":"Admin1","days":1000,"device":"IPF-E9A17C8D003B","status":"CHẠY"},{"key":"ATHAO","days":1000,"device":"IPF-C3C9B2A8406D","status":"CHẠY"},{"key":"TTT","days":1,"device":"IPF-E8084CAC1418","status":"CHẠY"},{"key":"111","days":1,"device":"IPF-4CE44B7C2A8A","status":"CHẠY"},{"key":"666","days":133,"device":"","status":"CHẠY"},{"key":"333","days":333,"device":"","status":""}];

function doGet(e) { return handle_(e); }
function doPost(e) { return handle_(e); }

function handle_(e) {
  e = e || {};
  var p = e.parameter || {};
  if (e.postData && e.postData.contents) {
    try {
      if ((e.postData.type || "").indexOf("json") >= 0) {
        var j = JSON.parse(e.postData.contents || "{}");
        p.key = p.key || j.key || "";
        p.udid = p.udid || j.udid || "";
        p.nonce = p.nonce || j.nonce || "";
      }
    } catch (err) {}
  }
  var out = validateKey_(String(p.key || ""), String(p.udid || ""), String(p.nonce || "0"));
  return ContentService.createTextOutput(JSON.stringify(out)).setMimeType(ContentService.MimeType.JSON);
}

function validateKey_(key, udid, nonce) {
  var ts = Math.floor(Date.now() / 1000);
  key = (key || "").trim();
  udid = (udid || "").trim();
  nonce = (nonce || "").trim() || "0";
  if (!key) return response_(false, "need_key", "", 0, nonce, ts);
  var rows = EMBEDDED_ROWS || [];
  var row = null;
  for (var i = 0; i < rows.length; i++) {
    if (rows[i].key === key) { row = rows[i]; break; }
  }
  if (!row) {
    var low = key.toLowerCase();
    for (var j = 0; j < rows.length; j++) {
      if (String(rows[j].key).toLowerCase() === low) { row = rows[j]; break; }
    }
  }
  if (!row) return response_(false, "not_found", "", 0, nonce, ts);
  if (!statusActive_(row.status)) return response_(false, "revoked", "", 0, nonce, ts);
  var days = parseInt(row.days, 10) || 0;
  if (days <= 0) return response_(false, "expired", "", 0, nonce, ts);
  var sheetDev = (row.device || "").trim();
  var binds = loadBinds_();
  var bound = sheetDev || String(binds[key] || "").trim();
  if (bound) {
    if (!devicesMatch_(bound, udid)) return response_(false, "wrong_device", "", 0, nonce, ts);
  } else if (udid) {
    binds[key] = udid;
    binds[key + "__bound_at"] = new Date().toISOString();
    saveBinds_(binds);
  }
  var expiry = new Date(Date.now() + days * 86400000).toISOString().replace(/\.\d{3}Z$/, "Z");
  return response_(true, "ok", expiry, days, nonce, ts);
}

function response_(ok, status, expiry, daysLeft, nonce, ts) {
  expiry = expiry || "";
  daysLeft = parseInt(daysLeft, 10) || 0;
  nonce = nonce || "";
  ts = parseInt(ts, 10) || Math.floor(Date.now() / 1000);
  return {
    ok: !!ok, status: status, expiry: expiry, daysLeft: daysLeft,
    ts: ts, nonce: nonce, sig: sign_(!!ok, status, expiry, daysLeft, ts, nonce)
  };
}

function sign_(ok, status, expiry, daysLeft, ts, nonce) {
  var msg = (ok ? "1" : "0") + "|" + status + "|" + expiry + "|" + daysLeft + "|" + ts + "|" + nonce;
  var raw = Utilities.computeHmacSha256Signature(msg, HMAC_SECRET);
  return raw.map(function (b) {
    var v = (b < 0 ? b + 256 : b).toString(16);
    return v.length === 1 ? "0" + v : v;
  }).join("");
}

function statusActive_(st) {
  var s = String(st || "").trim().toUpperCase();
  if (!s) return false;
  var ascii = s.replace(/Ạ/g,"A").replace(/Ă/g,"A").replace(/Â/g,"A").replace(/Ê/g,"E").replace(/Ô/g,"O").replace(/Ơ/g,"O").replace(/Ư/g,"U");
  return s === "CHẠY" || s === "CHAY" || s === "ACTIVE" || s === "OK" || s === "RUN" || s === "1" || s === "TRUE" || s === "YES" || ascii.indexOf("CHAY") >= 0;
}

function devicesMatch_(sheetDev, udid) {
  if (!sheetDev) return true;
  var a = String(sheetDev).trim().toUpperCase();
  var b = String(udid || "").trim().toUpperCase();
  if (a === b) return true;
  if (a.slice(-b.length) === b || b.slice(-a.length) === a) return true;
  var prefixes = ["IPF-", "HIOSV3|", "HIOS-", "DISO-"];
  for (var i = 0; i < prefixes.length; i++) {
    var p = prefixes[i];
    if (a.indexOf(p) === 0) {
      var a2 = a.substring(p.length);
      if (a2 === b || b.slice(-a2.length) === a2) return true;
    }
    if (b.indexOf(p) === 0) {
      var b2 = b.substring(p.length);
      if (a === b2 || a.slice(-b2.length) === b2) return true;
    }
  }
  return false;
}

function loadBinds_() {
  var raw = PropertiesService.getScriptProperties().getProperty("BINDS_JSON");
  if (!raw) return {};
  try { return JSON.parse(raw); } catch (e) { return {}; }
}
function saveBinds_(binds) {
  PropertiesService.getScriptProperties().setProperty("BINDS_JSON", JSON.stringify(binds));
}
