#!/usr/bin/env python3
"""Public always-on license without PC / same Wi‑Fi.

How it works (simple & reliable):
1) Python reads the public Google Sheet CSV (same sheet as shop).
2) Embeds key rows into Apps Script (no UrlFetch inside web app).
3) Deploys web app as Anyone — works like the ping test (no 403).
4) Customers hit the public /exec URL from any network.

Run this when you add/change keys (or schedule it on PC every N minutes).
The web app itself stays online 24/7 on Google — PC not needed for activation.
"""
from __future__ import annotations

import csv
import io
import json
import time
import urllib.error
import urllib.parse
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "license_server" / "ACTIVE_URL.txt"
SCRIPT_ID = "15ZQ7MX-YD4oFyYj8lOB76ydyGyd3kRWBK5kdP_f8wuAy_XZ7UUm4MFiz"
SHEET_ID = "1cnfHaeZc1SfDCQZGWI4CDV3vXIT6kGxgCCbVwhPGyno"
SHEET_CSV = (
    f"https://docs.google.com/spreadsheets/d/{SHEET_ID}/export?format=csv&gid=0"
)
HMAC_SECRET = "hF9kQ2mZ7vX1pR4nL8wB6cT3yD5sG0aJeU2iO9rK4lM7nP1qV8xZ3bN6"


def token() -> str:
    d = json.loads((Path.home() / ".clasprc.json").read_text(encoding="utf-8"))
    return d["tokens"]["default"]["access_token"]


def api(method: str, url: str, body: dict | None = None):
    data = None if body is None else json.dumps(body).encode("utf-8")
    req = urllib.request.Request(
        url,
        data=data,
        method=method,
        headers={
            "Authorization": f"Bearer {token()}",
            "Content-Type": "application/json",
        },
    )
    with urllib.request.urlopen(req, timeout=90) as r:
        raw = r.read()
        return json.loads(raw.decode()) if raw else None


def fetch_sheet_rows() -> list[dict]:
    req = urllib.request.Request(SHEET_CSV, headers={"User-Agent": "DisoSync/1.0"})
    with urllib.request.urlopen(req, timeout=30) as r:
        text = r.read().decode("utf-8", errors="replace")
    rows_in = list(csv.reader(io.StringIO(text)))
    if not rows_in:
        return []
    header = None
    start = 0
    for i, row in enumerate(rows_in):
        joined = ",".join(row).lower()
        if "key" in joined and (
            "hạn" in joined
            or "han" in joined
            or "id" in joined
            or "tình" in joined
            or "tinh" in joined
        ):
            header = [c.strip() for c in row]
            start = i + 1
            break
    if header is None:
        header = [c.strip() for c in rows_in[0]]
        start = 1

    def col(*names: str) -> int | None:
        low = [h.lower() for h in header]
        for n in names:
            for i, h in enumerate(low):
                if n in h:
                    return i
        return None

    i_key = col("key")
    i_days = col("hạn", "han", "days", "sử dụng", "su dung")
    i_dev = col("id máy", "id may", "máy", "may", "device", "udid")
    i_st = col("tình trạng", "tinh trang", "status", "trạng")
    out = []
    for row in rows_in[start:]:
        if not row or all(not (c or "").strip() for c in row):
            continue

        def get(idx):
            if idx is None or idx >= len(row):
                return ""
            return (row[idx] or "").strip()

        key = get(i_key)
        if not key:
            continue
        days_s = get(i_days)
        try:
            days = int(float(days_s)) if days_s else 0
        except ValueError:
            days = 0
        out.append(
            {
                "key": key,
                "days": days,
                "device": get(i_dev),
                "status": get(i_st),
            }
        )
    return out


def build_code(rows: list[dict]) -> str:
    # Compact JSON for embed
    embedded = json.dumps(rows, ensure_ascii=False, separators=(",", ":"))
    # Escape for JS string in single quotes? Use JSON directly as JS literal
    return f"""
// Auto-generated by sync_sheet_public_license.py — do not edit by hand
var HMAC_SECRET = "{HMAC_SECRET}";
var EMBEDDED_ROWS = {embedded};

function doGet(e) {{ return handle_(e); }}
function doPost(e) {{ return handle_(e); }}

function handle_(e) {{
  e = e || {{}};
  var p = e.parameter || {{}};
  if (e.postData && e.postData.contents) {{
    try {{
      if ((e.postData.type || "").indexOf("json") >= 0) {{
        var j = JSON.parse(e.postData.contents || "{{}}");
        p.key = p.key || j.key || "";
        p.udid = p.udid || j.udid || "";
        p.nonce = p.nonce || j.nonce || "";
      }}
    }} catch (err) {{}}
  }}
  var out = validateKey_(String(p.key || ""), String(p.udid || ""), String(p.nonce || "0"));
  return ContentService.createTextOutput(JSON.stringify(out)).setMimeType(ContentService.MimeType.JSON);
}}

function validateKey_(key, udid, nonce) {{
  var ts = Math.floor(Date.now() / 1000);
  key = (key || "").trim();
  udid = (udid || "").trim();
  nonce = (nonce || "").trim() || "0";
  if (!key) return response_(false, "need_key", "", 0, nonce, ts);
  var rows = EMBEDDED_ROWS || [];
  var row = null;
  for (var i = 0; i < rows.length; i++) {{
    if (rows[i].key === key) {{ row = rows[i]; break; }}
  }}
  if (!row) {{
    var low = key.toLowerCase();
    for (var j = 0; j < rows.length; j++) {{
      if (String(rows[j].key).toLowerCase() === low) {{ row = rows[j]; break; }}
    }}
  }}
  if (!row) return response_(false, "not_found", "", 0, nonce, ts);
  if (!statusActive_(row.status)) return response_(false, "revoked", "", 0, nonce, ts);
  var days = parseInt(row.days, 10) || 0;
  if (days <= 0) return response_(false, "expired", "", 0, nonce, ts);
  var sheetDev = (row.device || "").trim();
  var binds = loadBinds_();
  var bound = sheetDev || String(binds[key] || "").trim();
  if (bound) {{
    if (!devicesMatch_(bound, udid)) return response_(false, "wrong_device", "", 0, nonce, ts);
  }} else if (udid) {{
    binds[key] = udid;
    binds[key + "__bound_at"] = new Date().toISOString();
    saveBinds_(binds);
  }}
  var expiry = new Date(Date.now() + days * 86400000).toISOString().replace(/\\.\\d{{3}}Z$/, "Z");
  return response_(true, "ok", expiry, days, nonce, ts);
}}

function response_(ok, status, expiry, daysLeft, nonce, ts) {{
  expiry = expiry || "";
  daysLeft = parseInt(daysLeft, 10) || 0;
  nonce = nonce || "";
  ts = parseInt(ts, 10) || Math.floor(Date.now() / 1000);
  return {{
    ok: !!ok, status: status, expiry: expiry, daysLeft: daysLeft,
    ts: ts, nonce: nonce, sig: sign_(!!ok, status, expiry, daysLeft, ts, nonce)
  }};
}}

function sign_(ok, status, expiry, daysLeft, ts, nonce) {{
  var msg = (ok ? "1" : "0") + "|" + status + "|" + expiry + "|" + daysLeft + "|" + ts + "|" + nonce;
  var raw = Utilities.computeHmacSha256Signature(msg, HMAC_SECRET);
  return raw.map(function (b) {{
    var v = (b < 0 ? b + 256 : b).toString(16);
    return v.length === 1 ? "0" + v : v;
  }}).join("");
}}

function statusActive_(st) {{
  var s = String(st || "").trim().toUpperCase();
  if (!s) return false;
  var ascii = s.replace(/Ạ/g,"A").replace(/Ă/g,"A").replace(/Â/g,"A").replace(/Ê/g,"E").replace(/Ô/g,"O").replace(/Ơ/g,"O").replace(/Ư/g,"U");
  return s === "CHẠY" || s === "CHAY" || s === "ACTIVE" || s === "OK" || s === "RUN" || s === "1" || s === "TRUE" || s === "YES" || ascii.indexOf("CHAY") >= 0;
}}

function devicesMatch_(sheetDev, udid) {{
  if (!sheetDev) return true;
  var a = String(sheetDev).trim().toUpperCase();
  var b = String(udid || "").trim().toUpperCase();
  if (a === b) return true;
  if (a.slice(-b.length) === b || b.slice(-a.length) === a) return true;
  var prefixes = ["IPF-", "HIOSV3|", "HIOS-", "DISO-"];
  for (var i = 0; i < prefixes.length; i++) {{
    var p = prefixes[i];
    if (a.indexOf(p) === 0) {{
      var a2 = a.substring(p.length);
      if (a2 === b || b.slice(-a2.length) === a2) return true;
    }}
    if (b.indexOf(p) === 0) {{
      var b2 = b.substring(p.length);
      if (a === b2 || a.slice(-b2.length) === b2) return true;
    }}
  }}
  return false;
}}

function loadBinds_() {{
  var raw = PropertiesService.getScriptProperties().getProperty("BINDS_JSON");
  if (!raw) return {{}};
  try {{ return JSON.parse(raw); }} catch (e) {{ return {{}}; }}
}}
function saveBinds_(binds) {{
  PropertiesService.getScriptProperties().setProperty("BINDS_JSON", JSON.stringify(binds));
}}
""".strip()


def test_url(url: str) -> dict | None:
    data = urllib.parse.urlencode(
        {
            "key": "Admin",
            "udid": "IPF-4CE44B7C2A8A",
            "nonce": "sync1",
            "ts": str(int(time.time())),
        }
    ).encode()
    req = urllib.request.Request(
        url,
        data=data,
        headers={
            "Content-Type": "application/x-www-form-urlencoded",
            "User-Agent": "Mozilla/5.0 DisoSync/1.0",
        },
    )
    try:
        with urllib.request.urlopen(req, timeout=60) as r:
            body = r.read().decode()
            print("TEST:", body[:350])
            if body.strip().startswith("{"):
                return json.loads(body)
    except urllib.error.HTTPError as e:
        print("TEST HTTP", e.code, e.read()[:180])
    except Exception as e:
        print("TEST ERR", e)
    return None


def main() -> int:
    rows = fetch_sheet_rows()
    print(f"sheet keys: {len(rows)} -> {[r['key'] for r in rows[:12]]}")
    code = build_code(rows)
    (ROOT / "license_server" / "Code.gs").write_text(code + "\n", encoding="utf-8")

    # No oauthScopes — Properties + HMAC only (works like ping)
    manifest = {
        "timeZone": "Asia/Ho_Chi_Minh",
        "exceptionLogging": "STACKDRIVER",
        "runtimeVersion": "V8",
        "webapp": {"executeAs": "USER_DEPLOYING", "access": "ANYONE_ANONYMOUS"},
    }
    content = {
        "files": [
            {"name": "Code", "type": "SERVER_JS", "source": code},
            {"name": "appsscript", "type": "JSON", "source": json.dumps(manifest)},
        ]
    }
    api("PUT", f"https://script.googleapis.com/v1/projects/{SCRIPT_ID}/content", content)
    print("pushed")
    ver = api(
        "POST",
        f"https://script.googleapis.com/v1/projects/{SCRIPT_ID}/versions",
        {"description": f"sync {len(rows)} keys"},
    )
    dep = api(
        "POST",
        f"https://script.googleapis.com/v1/projects/{SCRIPT_ID}/deployments",
        {
            "versionNumber": ver["versionNumber"],
            "description": "Diso public embedded keys",
            "manifestFileName": "appsscript",
        },
    )
    url = dep["entryPoints"][0]["webApp"]["url"]
    OUT.write_text(url + "\n", encoding="utf-8")
    print("ACTIVE_URL", url)

    # small wait for propagation
    time.sleep(3)
    j = test_url(url)
    if not j or "status" not in j:
        time.sleep(5)
        j = test_url(url)
    if j and "status" in j:
        print("PUBLIC OK", j.get("ok"), j.get("status"), j.get("daysLeft"))
        return 0
    print("FAIL public test")
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
